### ISSUE TITLE
Change default branch to dev

### ISSUE THREAD

**Issue by mtheoryx** [NinjaBunny9000/TwitchTeamShoutoutBot#10]
It looks like the default branch for this repo is master. If that is what you want, that is fine.

However, that means that opening a PR from a fork will automatically select that branch, instead of dev.

The setting is Settings > Branches > Default branch > Choose from dropdown and click update.

**Comment by bun9000** [comment]
good call, i'll change that now. thanks for the heads up!

**Comment by bun9000** [comment]
doneskies
